## 1. What is a Python library? Why do we use Python libraries?

####   Python libraries are collections of pre-written code and functions that extend the capabilities of the Python programming language
####   They provide a wide range of tools and modules for various tasks, making it easier for developers to work on specific tasks without reinventing the wheel.

## 2. What is the difference between Numpy array and List?

### 1. Datatype :
#### NumPy arrays store elements of the same data type i.e homogeneous data while list can be homogeneous or heterogeneous.

### 2. Contiguous Memory:
#### NumPy arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.
#### Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.

### 3.Performance :
#### NumPy arrays are optimized for numerical computations, with efficient element-wise operations and mathematical functions. These operations are implemented in C, resulting in faster performance than equivalent operations on lists.
#### Lists are not optimized for numerical computations and may have slower mathematical operations due to Python’s interpretation overhead.


## 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
import numpy as np
arr=np.array([[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]])

In [4]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
# Shape of array
arr.shape

(3, 4)

In [7]:
# Size of array
arr.size

12

In [8]:
# Dimension of array
arr.ndim

2

## 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [9]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
# First row of array
arr[0]

array([1, 2, 3, 4])

## 5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [12]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [13]:
# Element at third row and fourth column
arr[2][3]

12

## 6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [41]:
arr=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
flat_arr=arr.flatten()
odd_indexed_elements=[]
for i in range(0,flat_arr.size):
    if i%2==1:
        odd_indexed_elements.append(flat_arr[i])
        
print("Odd indexed elements are as below : \n",odd_indexed_elements)

Odd indexed elements are as below : 
 [2, 4, 6, 8, 10, 12]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [24]:
import numpy as np
arr1=np.random.rand(3,3)
arr1

array([[0.66201616, 0.62476466, 0.74404194],
       [0.53418588, 0.36259622, 0.86577841],
       [0.7444555 , 0.03119979, 0.88458426]])

## 8. Describe the difference between np.random.rand and np.random.randn?

### random. rand() produces random numbers from a uniform distribution over the interval [0, 1), while np. random. randn() generates random numbers from a standard normal distribution

## 9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [25]:
arr2=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [26]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
np.expand_dims(arr2,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

## 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [29]:
arr3=np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [30]:
# transpose of given matrix is as below:
arr3.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

## 11. Consider the following matrix:

Matrix A : [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B:[[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


## Perform the following operation using Python
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrices
4. Subtract matrix B from A
5. Divide matrix B by A

In [31]:
A=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

B=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

### 1. Index wise multiplication

In [32]:
A * B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### 2. Matrix multiplication

In [35]:
A @ B.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

### 3. Add both the matrices

In [34]:
A + B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

### 4. Subtract matrix B from A

In [36]:
A-B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### 5. Divide matrix B by A

In [37]:
B/A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 12.  Which function in Numpy can be used to swap the byte order of an array?

### For byte swapping, the Numpy library offers the method called “byteswap()”, which is basically used to swap the byte order of the data stored in memory or one endianness to another.

## 13.  What is the significance of the np.linalg.inv function?

### We use numpy. linalg. inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

## 14. What does the np.reshape function do, and how is it used?

### np.reshape function gives a new shape to an array without changing its data

### It is used as follows:


In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## 15. What is broadcasting in Numpy?

### Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops.